defaultSemverRangePrefix: ""

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nmMode: hardlinks-local

nodeLinker: pnp

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

preferInteractive: true

packageExtensions:
  # Resolver conflitos específicos
  "pacote@*":
    peerDependencies:
      "react": "*"
